//! Metrics and reporting for autonomous improvement sessions.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::Duration;

use crate::safety::SafetyStop;

/// Per-strategy task metrics.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StrategyMetrics {
    /// Number of tasks generated by this strategy.
    pub tasks_generated: u32,
    /// Number of tasks attempted.
    pub tasks_attempted: u32,
    /// Number of tasks that succeeded.
    pub tasks_succeeded: u32,
}

/// Comparison result between two execution paths.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComparisonResult {
    /// Whether both paths succeeded.
    pub both_succeeded: bool,
    /// Whether both paths failed.
    pub both_failed: bool,
    /// Whether the diffs match.
    pub diffs_match: bool,
    /// Difference in iteration counts.
    pub iteration_delta: i32,
    /// Errors specific to the bridge path.
    pub bridge_specific_errors: Vec<String>,
}

/// Session-wide metrics tracking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMetrics {
    /// Timestamp when the session started.
    pub start_time: DateTime<Utc>,
    /// Total number of tasks attempted.
    pub tasks_attempted: u32,
    /// Total number of tasks that succeeded.
    pub tasks_succeeded: u32,
    /// Total number of tasks that failed.
    pub tasks_failed: u32,
    /// Metrics broken down by strategy name.
    pub per_strategy: HashMap<String, StrategyMetrics>,
    /// Results of dual-path comparisons.
    pub comparisons: Vec<ComparisonResult>,
    /// Estimated total cost in USD.
    pub total_cost: f64,
    /// Total iteration count across all tasks.
    pub total_iterations: u32,
    /// Commit hashes produced during the session.
    pub commits: Vec<String>,
}

impl SessionMetrics {
    /// Create a new session metrics instance starting now.
    pub fn new() -> Self {
        Self {
            start_time: Utc::now(),
            tasks_attempted: 0,
            tasks_succeeded: 0,
            tasks_failed: 0,
            per_strategy: HashMap::new(),
            comparisons: Vec::new(),
            total_cost: 0.0,
            total_iterations: 0,
            commits: Vec::new(),
        }
    }

    /// Record a task attempt for the given strategy.
    pub fn record_attempt(&mut self, strategy: &str) {
        self.tasks_attempted += 1;
        self.per_strategy
            .entry(strategy.to_string())
            .or_default()
            .tasks_attempted += 1;
    }

    /// Record a successful task for the given strategy with its iteration count.
    pub fn record_success(&mut self, strategy: &str, iterations: u32) {
        self.tasks_succeeded += 1;
        self.total_iterations += iterations;
        self.per_strategy
            .entry(strategy.to_string())
            .or_default()
            .tasks_succeeded += 1;
    }

    /// Record a failed task for the given strategy.
    pub fn record_failure(&mut self, strategy: &str) {
        self.tasks_failed += 1;
        self.per_strategy
            .entry(strategy.to_string())
            .or_default()
            .tasks_attempted += 1;
    }

    /// Record the number of tasks generated by a strategy.
    pub fn record_generated(&mut self, strategy: &str, count: u32) {
        self.per_strategy
            .entry(strategy.to_string())
            .or_default()
            .tasks_generated += count;
    }

    /// Record a dual-path comparison result.
    pub fn record_comparison(&mut self, comparison: ComparisonResult) {
        self.comparisons.push(comparison);
    }

    /// Record a commit hash produced during the session.
    pub fn record_commit(&mut self, hash: String) {
        self.commits.push(hash);
    }

    /// Compute the success rate as a fraction between 0.0 and 1.0.
    pub fn success_rate(&self) -> f64 {
        if self.tasks_attempted == 0 {
            0.0
        } else {
            self.tasks_succeeded as f64 / self.tasks_attempted as f64
        }
    }
}

impl Default for SessionMetrics {
    fn default() -> Self {
        Self::new()
    }
}

/// Complete session report with serialization to JSON and Markdown.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionReport {
    /// Aggregated session metrics.
    pub metrics: SessionMetrics,
    /// Total wall-clock duration of the session.
    #[serde(with = "duration_serde")]
    pub duration: Duration,
    /// Human-readable reason the session stopped, if a safety stop occurred.
    pub safety_stop_reason: Option<String>,
}

mod duration_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use std::time::Duration;

    pub fn serialize<S>(d: &Duration, s: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        d.as_secs_f64().serialize(s)
    }

    pub fn deserialize<'de, D>(d: D) -> Result<Duration, D::Error>
    where
        D: Deserializer<'de>,
    {
        let secs = f64::deserialize(d)?;
        Ok(Duration::from_secs_f64(secs))
    }
}

impl SessionReport {
    /// Create a new session report from metrics, duration, and optional stop reason.
    pub fn new(metrics: SessionMetrics, duration: Duration, stop_reason: Option<SafetyStop>) -> Self {
        Self {
            metrics,
            duration,
            safety_stop_reason: stop_reason.map(|r| r.to_string()),
        }
    }

    /// Serialize the report to pretty-printed JSON.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    /// Render the report as a Markdown document.
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();
        md.push_str("# Self-Improvement Session Report\n\n");
        md.push_str(&format!(
            "**Date**: {}\n",
            self.metrics.start_time.format("%Y-%m-%d %H:%M:%S UTC")
        ));
        md.push_str(&format!("**Duration**: {:.1}s\n", self.duration.as_secs_f64()));
        md.push_str(&format!(
            "**Success Rate**: {:.1}%\n\n",
            self.metrics.success_rate() * 100.0
        ));

        md.push_str("## Summary\n\n");
        md.push_str("| Metric | Value |\n|--------|-------|\n");
        md.push_str(&format!("| Tasks Attempted | {} |\n", self.metrics.tasks_attempted));
        md.push_str(&format!("| Tasks Succeeded | {} |\n", self.metrics.tasks_succeeded));
        md.push_str(&format!("| Tasks Failed | {} |\n", self.metrics.tasks_failed));
        md.push_str(&format!("| Total Iterations | {} |\n", self.metrics.total_iterations));
        md.push_str(&format!("| Estimated Cost | ${:.4} |\n", self.metrics.total_cost));
        md.push_str(&format!("| Commits | {} |\n", self.metrics.commits.len()));

        if !self.metrics.per_strategy.is_empty() {
            md.push_str("\n## Per-Strategy Breakdown\n\n");
            md.push_str("| Strategy | Generated | Attempted | Succeeded |\n");
            md.push_str("|----------|-----------|-----------|----------|\n");
            for (name, stats) in &self.metrics.per_strategy {
                md.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    name, stats.tasks_generated, stats.tasks_attempted, stats.tasks_succeeded
                ));
            }
        }

        if !self.metrics.comparisons.is_empty() {
            md.push_str("\n## Dual-Path Comparisons\n\n");
            let both_ok = self.metrics.comparisons.iter().filter(|c| c.both_succeeded).count();
            let diffs_match = self.metrics.comparisons.iter().filter(|c| c.diffs_match).count();
            md.push_str(&format!(
                "- Both paths succeeded: {}/{}\n",
                both_ok,
                self.metrics.comparisons.len()
            ));
            md.push_str(&format!("- Diffs matched: {}/{}\n", diffs_match, both_ok));
        }

        if let Some(ref reason) = self.safety_stop_reason {
            md.push_str(&format!("\n## Stop Reason\n\n{reason}\n"));
        }

        if !self.metrics.commits.is_empty() {
            md.push_str("\n## Commits\n\n");
            for hash in &self.metrics.commits {
                md.push_str(&format!("- `{hash}`\n"));
            }
        }

        md
    }

    /// Save the report to both JSON and Markdown files in the given directory.
    pub fn save(&self, output_dir: &str) -> anyhow::Result<()> {
        std::fs::create_dir_all(output_dir)?;
        let timestamp = self.metrics.start_time.format("%Y%m%d-%H%M%S").to_string();

        let json_path = format!("{output_dir}/session-{timestamp}.json");
        std::fs::write(&json_path, self.to_json()?)?;

        let md_path = format!("{output_dir}/session-{timestamp}.md");
        std::fs::write(&md_path, self.to_markdown())?;

        tracing::info!("Session report saved to {json_path} and {md_path}");
        Ok(())
    }
}
