#!/usr/bin/env node
// brainwires-chat-pwa web build script.
//
// Responsibilities:
//   1. esbuild-bundle src/boot.js → app.js (esm, sourcemap, es2022).
//      ./pkg/* is left external — wasm-pack output is loaded as a
//      module at runtime, not bundled.
//   2. esbuild-bundle sw.source.js → sw.bundle.js (IIFE, es2022).
//      IIFE because some mobile browsers still ship without
//      type=module SW support; an IIFE works everywhere classic SWs do.
//      sw.bundle.js is a build intermediate (gitignored).
//   3. Patch sw.bundle.js → sw.js by substituting the __SRI_HASHES__
//      placeholder with a JSON object mapping each cacheable static
//      asset to its base64 sha256. sw.js itself is excluded from the
//      table — workers can't verify themselves.
//   4. Emit build-info.js with BUILD_TIME + BUILD_GIT exports.
//
// Modes:
//   node build.mjs            — one-shot build
//   node build.mjs --watch    — esbuild ctx.watch() (no server)
//   node build.mjs --serve    — esbuild ctx.serve() on 127.0.0.1:3000.

import * as esbuild from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const argv = new Set(process.argv.slice(2));
const isWatch = argv.has('--watch');
const isServe = argv.has('--serve');

// ── esbuild config: app bundle ──────────────────────────────────
const appConfig = {
    entryPoints: [join(__dirname, 'src/boot.js')],
    bundle: true,
    outfile: join(__dirname, 'app.js'),
    format: 'esm',
    sourcemap: true,
    target: ['es2022'],
    absWorkingDir: __dirname,
    // wasm-pack output is loaded at runtime via dynamic import; never bundle it.
    external: [
        './pkg/brainwires_chat_pwa.js',
        './pkg/*',
    ],
    logLevel: 'info',
};

// ── esbuild config: service-worker bundle ───────────────────────
// IIFE so the file can be registered as a classic worker on every
// browser that ships ServiceWorker — type=module SWs are broadly
// supported but iOS lagged for a long while; IIFE is a safe floor.
const swConfig = {
    entryPoints: [join(__dirname, 'sw.source.js')],
    bundle: true,
    outfile: join(__dirname, 'sw.bundle.js'),
    format: 'iife',
    sourcemap: false,
    target: ['es2022'],
    absWorkingDir: __dirname,
    platform: 'browser',
    logLevel: 'info',
};

// ── SRI patching ────────────────────────────────────────────────
// Files pinned with SRI hashes. sw.js is excluded — a service worker
// cannot meaningfully verify its own bytes against a hash that lives
// inside it.
const STATIC_ASSETS = [
    'index.html',
    'manifest.json',
    'app.js',
    'styles.css',
    'pkg/brainwires_chat_pwa.js',
    'pkg/brainwires_chat_pwa_bg.wasm',
    'icons/icon-192.png',
    'icons/icon-512.png',
];

function sha256Base64(absPath) {
    return createHash('sha256').update(readFileSync(absPath)).digest('base64');
}

function patchServiceWorker() {
    const bundlePath = join(__dirname, 'sw.bundle.js');
    const outPath = join(__dirname, 'sw.js');
    if (!existsSync(bundlePath)) {
        console.warn('  sw.bundle.js missing, skipping sw.js generation');
        return;
    }
    const source = readFileSync(bundlePath, 'utf8');

    const hashes = {};
    const skipped = [];
    for (const rel of STATIC_ASSETS) {
        const abs = join(__dirname, rel);
        if (!existsSync(abs)) { skipped.push(rel); continue; }
        hashes[rel] = `sha256-${sha256Base64(abs)}`;
    }

    const marker = '__SRI_HASHES__';
    if (!source.includes(marker)) {
        throw new Error(`sw.bundle.js missing ${marker} placeholder (esbuild may have stripped it)`);
    }
    const out = source.replace(marker, JSON.stringify(hashes, null, 4));
    writeFileSync(outPath, out);
    const note = skipped.length ? `, ${skipped.length} skipped` : '';
    console.log(`  sw.js generated (${Object.keys(hashes).length} assets hashed${note})`);
}

function generateBuildInfo() {
    const ts = new Date().toISOString();
    let sha = 'unknown';
    try { sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch {}
    const body =
        `// generated by build.mjs — do not edit\n` +
        `export const BUILD_TIME = '${ts}';\n` +
        `export const BUILD_GIT = '${sha}';\n`;
    writeFileSync(join(__dirname, 'build-info.js'), body);
    console.log(`  build-info: ${ts} (${sha})`);
}

async function buildAll() {
    const t0 = performance.now();
    await esbuild.build(appConfig);
    await esbuild.build(swConfig);
    console.log(`  bundled in ${Math.round(performance.now() - t0)}ms`);
    patchServiceWorker();
    generateBuildInfo();
}

// ── Run ─────────────────────────────────────────────────────────
if (isServe) {
    const ctx = await esbuild.context(appConfig);
    const swCtx = await esbuild.context(swConfig);
    await ctx.rebuild();
    await swCtx.rebuild();
    patchServiceWorker();
    generateBuildInfo();
    await ctx.watch();
    await swCtx.watch();
    const server = await ctx.serve({
        host: '127.0.0.1',
        port: 3000,
        servedir: __dirname,
    });
    console.log(`Serving http://${server.host}:${server.port}/`);
} else if (isWatch) {
    const ctx = await esbuild.context(appConfig);
    const swCtx = await esbuild.context(swConfig);
    await ctx.rebuild();
    await swCtx.rebuild();
    patchServiceWorker();
    generateBuildInfo();
    await ctx.watch();
    await swCtx.watch();
    console.log('Watching for changes...');
} else {
    await buildAll();
}
