#!/usr/bin/env node
// brainwires-chat-pwa web build script.
//
// Responsibilities:
//   1. esbuild-bundle src/boot.js → app.js (esm, sourcemap, es2022).
//      ./pkg/* is left external — wasm-pack output is loaded as a
//      module at runtime, not bundled.
//   2. Patch sw.source.js → sw.js by substituting the __SRI_HASHES__
//      placeholder with a JSON object mapping each cacheable static
//      asset to its base64 sha256 (parolnet pattern).
//   3. Emit build-info.js with BUILD_TIME + BUILD_GIT exports.
//
// Modes:
//   node build.mjs            — one-shot build
//   node build.mjs --watch    — esbuild ctx.watch() (no server)
//   node build.mjs --serve    — esbuild ctx.serve() on 127.0.0.1:3000.
//                                If you'd rather use `npx serve` against
//                                this directory, drop --serve and run
//                                `npx serve .` separately; build.mjs
//                                doesn't care.

import * as esbuild from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const argv = new Set(process.argv.slice(2));
const isWatch = argv.has('--watch');
const isServe = argv.has('--serve');

// ── esbuild config ──────────────────────────────────────────────
const esbuildConfig = {
    entryPoints: [join(__dirname, 'src/boot.js')],
    bundle: true,
    outfile: join(__dirname, 'app.js'),
    format: 'esm',
    sourcemap: true,
    target: ['es2022'],
    absWorkingDir: __dirname,
    // wasm-pack output is loaded at runtime via dynamic import; never bundle it.
    external: [
        './pkg/brainwires_chat_pwa.js',
        './pkg/*',
    ],
    logLevel: 'info',
};

// ── SRI patching ────────────────────────────────────────────────
// The list of assets that need integrity pinning. Files that don't exist
// yet (e.g. before wasm-pack runs) are silently skipped; build.sh runs
// wasm-pack before this script, so on a real build all of these resolve.
const STATIC_ASSETS = [
    'index.html',
    'manifest.json',
    'app.js',
    'styles.css',
    'pkg/brainwires_chat_pwa.js',
    'pkg/brainwires_chat_pwa_bg.wasm',
    'icons/icon-192.png',
    'icons/icon-512.png',
];

function sha256Base64(absPath) {
    return createHash('sha256').update(readFileSync(absPath)).digest('base64');
}

function patchServiceWorker() {
    const sourcePath = join(__dirname, 'sw.source.js');
    const outPath = join(__dirname, 'sw.js');
    if (!existsSync(sourcePath)) {
        console.warn('  sw.source.js missing, skipping sw.js generation');
        return;
    }
    const source = readFileSync(sourcePath, 'utf8');

    const hashes = {};
    const skipped = [];
    for (const rel of STATIC_ASSETS) {
        const abs = join(__dirname, rel);
        if (!existsSync(abs)) { skipped.push(rel); continue; }
        hashes[rel] = `sha256-${sha256Base64(abs)}`;
    }

    const marker = '__SRI_HASHES__';
    if (!source.includes(marker)) {
        throw new Error(`sw.source.js missing ${marker} placeholder`);
    }
    const out = source.replace(marker, JSON.stringify(hashes, null, 4));
    writeFileSync(outPath, out);
    const note = skipped.length ? `, ${skipped.length} skipped` : '';
    console.log(`  sw.js generated (${Object.keys(hashes).length} assets hashed${note})`);
}

function generateBuildInfo() {
    const ts = new Date().toISOString();
    let sha = 'unknown';
    try { sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch {}
    const body =
        `// generated by build.mjs — do not edit\n` +
        `export const BUILD_TIME = '${ts}';\n` +
        `export const BUILD_GIT = '${sha}';\n`;
    writeFileSync(join(__dirname, 'build-info.js'), body);
    console.log(`  build-info: ${ts} (${sha})`);
}

// ── Run ─────────────────────────────────────────────────────────
async function oneShot() {
    const t0 = performance.now();
    await esbuild.build(esbuildConfig);
    console.log(`  bundled in ${Math.round(performance.now() - t0)}ms`);
    patchServiceWorker();
    generateBuildInfo();
}

if (isServe) {
    const ctx = await esbuild.context(esbuildConfig);
    // Build once so app.js / sw.js / build-info.js exist before serving.
    await ctx.rebuild();
    patchServiceWorker();
    generateBuildInfo();
    await ctx.watch();
    const server = await ctx.serve({
        host: '127.0.0.1',
        port: 3000,
        servedir: __dirname,
    });
    console.log(`Serving http://${server.host}:${server.port}/`);
} else if (isWatch) {
    const ctx = await esbuild.context(esbuildConfig);
    await ctx.rebuild();
    patchServiceWorker();
    generateBuildInfo();
    await ctx.watch();
    console.log('Watching for changes...');
} else {
    await oneShot();
}
